/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './ng-airound-protocol.module';
import * as i2 from './ng-airound-protocol';
export const AiroundProtocolModuleNgFactory:i0.NgModuleFactory<i1.AiroundProtocolModule> = i0.ɵcmf(i1.AiroundProtocolModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(5120,
          i2.AiroundProtocolBuilder,i1.AiroundProtocolFactory,([] as any[])),i0.ɵmpd(512,
          i1.AiroundProtocolModule,i1.AiroundProtocolModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2VkZGllL0NPREUvQW5ndWxhci9hbmd1bGFyLWFpcm91bmQtcHJvdG9jb2wvc3JjL25nLWFpcm91bmQtcHJvdG9jb2wubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2VkZGllL0NPREUvQW5ndWxhci9hbmd1bGFyLWFpcm91bmQtcHJvdG9jb2wvc3JjL25nLWFpcm91bmQtcHJvdG9jb2wubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
